# SPDX-FileCopyrightText: 2026 German Federal Office for Information Security (BSI) <https://www.bsi.bund.de>
# Software-Engineering: 2026 Intevation GmbH <https://intevation.de>
#
# SPDX-License-Identifier: Apache-2.0

Listen 8080

LoadModule mpm_event_module modules/mod_mpm_event.so
LoadModule authz_core_module modules/mod_authz_core.so
LoadModule dir_module modules/mod_dir.so
LoadModule mime_module modules/mod_mime.so
LoadModule rewrite_module modules/mod_rewrite.so
LoadModule unixd_module modules/mod_unixd.so
LoadModule log_config_module modules/mod_log_config.so

ServerName localhost
ServerRoot /usr/local/apache2
TypesConfig conf/mime.types

DocumentRoot "/usr/local/apache2/htdocs"
DirectoryIndex index.html

ErrorLogFormat "[%{%Y-%m-%dT%H:%M:%S%z}t] [%l] [pid %P] %M"
ErrorLog /proc/self/fd/2
CustomLog /proc/self/fd/1 "[%{%Y-%m-%dT%H:%M:%S%z}t] \"%r\" %>s %b \"%{User-Agent}i\""

<Directory "/usr/local/apache2/htdocs">
    Options -Indexes
    AllowOverride None
    Require all granted
    RewriteEngine On
    RewriteCond %{REQUEST_FILENAME} !-f
    RewriteCond %{REQUEST_FILENAME} !-d
    RewriteRule . /index.html [L]
</Directory>
